### ISSUE TITLE
More elements in the XML response for Identify	

### ISSUE THREAD

**Issue by snorri** [LibreCat/Dancer-Plugin-Catmandu-OAI#13]
The following are allowed but can't be specified in the plugin:

- multiple entries for `adminEmail` (only one can be specified currently)
- `compression` (0 or more)
- `description` (0 ore more). This one is bit trickier because there is no fixed structure. Maybe just specify another template that is included?

**Comment by nicolasfranck** [comment]
I agree with the first two options. I'll see to it.
The description can be easily solved by just dropping a (list of) description(s) from the config.
It's not so hard to put xml-data in your yaml config. Why should a template be necessary?

**Comment by nicolasfranck** [comment]
See https://github.com/LibreCat/Dancer-Plugin-Catmandu-OAI/pull/14

**Comment by snorri** [comment]
No, probably it can work and is easier having it in the config. But how would you distinguish between what should be an attribute and what should be a sub-element in YAML? Use always arrays for elements and single values for attributes?

**Comment by nicolasfranck** [comment]
oh no, in the pull request ( as mentioned above ), one can just drop the xml data in the YAML config. No need to convert from hash to XML. Although it's not easy in the current YAML implementation for perl to embed XML ( you have to put everything on one line ).

**Comment by nics** [comment]
Included in release 0.0401
